import type { BundleInput } from '../lib/types.ts'

export function createCapCutBrief(input: BundleInput): string {
  return [
    `# CapCut Edit Brief: ${input.scenario.title}`,
    '',
    '## Goal',
    '',
    'Create a polished vertical Instagram Reels edit from the Flowrit screen recording.',
    '',
    '## Source Files',
    '',
    '- `source.mp4`: primary screen recording',
    '- `cover.png`: cover candidate',
    '- `screenshots/`: scene references',
    '- `caption.md`: posting copy and hashtags',
    '',
    '## Recommended Timeline',
    '',
    '- 0.0s-1.5s: Hook title overlay',
    '- 1.5s-8.0s: Show the client portal or dashboard context',
    '- 8.0s-18.0s: Show the key workflow steps',
    '- 18.0s-26.0s: Highlight the outcome and reliability',
    '- 26.0s-30.0s: CTA end card',
    '',
    '## Overlay Copy',
    '',
    '- Hook: "수정 요청과 납품 이력을 링크 하나로"',
    '- Middle: "고객은 진행 단계와 결과물을 직접 확인"',
    '- CTA: "Flowrit으로 프로젝트 응대 흐름을 정리하세요"',
    '',
    '## CapCut Settings',
    '',
    '- Canvas: 9:16 vertical',
    '- Export: 1080x1920 MP4 when possible',
    '- Captions: Korean, large enough for mobile',
    '- Music: commercial-safe background track only',
    '- Brand: clean SaaS tone, avoid heavy effects over UI text',
    '',
    '## Privacy Rules',
    '',
    '- Do not reveal emails, tokens, private URLs, payment data, or real customer names.',
    '- Use only the provided demo data.',
  ].join('\n')
}
